#!/usr/bin/env python3

import argparse
import json
import sys
from pathlib import Path

from utils import hrx_route_emit as route_emit
from utils import hrx_route_schema as route_schema
import validate_loom_routes as route_validator



ATTRIBUTE_INDICES = route_emit.ATTRIBUTE_INDICES
CPP_SCALAR_TYPES = route_emit.CPP_SCALAR_TYPES

UNSUPPORTED_REASON_BY_PREDICATE = {
    "contiguous": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    "same_shape": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "same_layout": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    "rank": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "field": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "src_absent": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "src_present": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "transients": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    "no_overlap": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    "same_or_disjoint_storage": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    "consumers_through_view": "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
}

ROUTE_FUNCTION_OPEN_TEMPLATE = """static ggml_backend_hrx_loom_op_response {function_name}(
        ggml_backend_hrx_loom_catalog * catalog,
        const ggml_backend_hrx_loom_op_request * request,
        ggml_backend_hrx_loom_execution_plan * plan) {{
    if (!catalog || !request || !request->op) {{
        return ggml_backend_hrx_loom_failed(nullptr);
    }}
    const ggml_tensor * node = request->op;
    if (node->op != {op}) {{
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
    }}
    const ggml_backend_hrx_loom_catalog_entry * entry = ggml_backend_hrx_loom_find_entry(catalog, {route_id_constant});
    if (!entry) {{
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_TARGET);
    }}"""

PLAN_SETUP_TEMPLATE = """
    if (ggml_backend_hrx_loom_match_only(plan)) {{
        return ggml_backend_hrx_loom_supported({route_id_constant});
    }}
    if (!request->bind_tensor) {{
        return ggml_backend_hrx_loom_failed({route_id_constant});
    }}
    *plan = {{}};"""

BIND_BUFFER_TEMPLATE = """    if (!ggml_backend_hrx_loom_bind_tensor(request, {tensor}, &{plan_expr}.bindings[{position}])) {{
        return ggml_backend_hrx_loom_failed({route_id_constant});
    }}"""

PACK_SCALAR_TEMPLATE = """    const {cpp_type} {name} = {value};
    std::memcpy({plan_expr}.constants + {offset}, &{name}, sizeof({name}));"""

DISPATCHER_CPP_HEADER_TEMPLATE = """// Generated by generate_loom_route_impl.py.

#include "loom-catalog/ggml-hrx-loom-catalog-runtime-internal.h"

#include <cstdio>
#include <cstring>

[[maybe_unused]] static int64_t ggml_backend_hrx_loom_tensor_permutation_axis(const ggml_tensor * tensor, const int axis) {
    int order[4] = {0, 1, 2, 3};
    for (int i = 1; i < 4; ++i) {
        const int value = order[i];
        int j = i - 1;
        while (j >= 0 && tensor->nb[order[j]] > tensor->nb[value]) {
            order[j + 1] = order[j];
            --j;
        }
        order[j + 1] = value;
    }
    return axis >= 0 && axis < 4 ? order[axis] : -1;
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensors_have_same_layout(
        const ggml_tensor * lhs,
        const ggml_tensor * rhs) {
    if (!lhs || !rhs) {
        return false;
    }
    for (int i = 0; i < 4; ++i) {
        if (lhs->nb[i] != rhs->nb[i]) {
            return false;
        }
    }
    return true;
}

[[maybe_unused]] static uintptr_t ggml_backend_hrx_loom_tensor_addr(const ggml_tensor * tensor) {
    const ggml_tensor * base = tensor && tensor->view_src ? tensor->view_src : tensor;
    return base ? reinterpret_cast<uintptr_t>(base->data) + tensor->view_offs : 0;
}

[[maybe_unused]] static const void * ggml_backend_hrx_loom_tensor_buffer(const ggml_tensor * tensor) {
    const ggml_tensor * base = tensor && tensor->view_src ? tensor->view_src : tensor;
    return base ? base->buffer : nullptr;
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensors_overlap(
        const ggml_tensor * lhs,
        const ggml_tensor * rhs) {
    if (!lhs || !rhs || ggml_backend_hrx_loom_tensor_buffer(lhs) != ggml_backend_hrx_loom_tensor_buffer(rhs)) {
        return false;
    }
    const uintptr_t lhs_begin = ggml_backend_hrx_loom_tensor_addr(lhs);
    const uintptr_t rhs_begin = ggml_backend_hrx_loom_tensor_addr(rhs);
    const uintptr_t lhs_end = lhs_begin + ggml_nbytes(lhs);
    const uintptr_t rhs_end = rhs_begin + ggml_nbytes(rhs);
    return lhs_begin < rhs_end && rhs_begin < lhs_end;
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensors_are_same_or_disjoint(
        const ggml_tensor * lhs,
        const ggml_tensor * rhs) {
    if (!lhs || !rhs) {
        return false;
    }
    const bool same =
        ggml_backend_hrx_loom_tensor_buffer(lhs) ==
            ggml_backend_hrx_loom_tensor_buffer(rhs) &&
        ggml_backend_hrx_loom_tensor_addr(lhs) ==
            ggml_backend_hrx_loom_tensor_addr(rhs) &&
        ggml_nbytes(lhs) == ggml_nbytes(rhs);
    return same || !ggml_backend_hrx_loom_tensors_overlap(lhs, rhs);
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_is_traversable_metadata_op(
        const ggml_tensor * tensor) {
    if (!tensor) {
        return false;
    }
    switch (tensor->op) {
        case GGML_OP_NONE:
        case GGML_OP_RESHAPE:
        case GGML_OP_VIEW:
        case GGML_OP_PERMUTE:
        case GGML_OP_TRANSPOSE:
            return true;
        default:
            return false;
    }
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensor_follows_metadata_path(
        const ggml_tensor * value,
        const ggml_tensor * source) {
    if (value == source) {
        return true;
    }
    while (value && ggml_backend_hrx_loom_is_traversable_metadata_op(value)) {
        value = value->src[0] ? value->src[0] : value->view_src;
        if (value == source) {
            return true;
        }
    }
    return false;
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensor_dag_edge_matches(
        const ggml_tensor * lhs,
        const ggml_tensor * rhs) {
    return ggml_backend_hrx_loom_tensor_follows_metadata_path(lhs, rhs) ||
           ggml_backend_hrx_loom_tensor_follows_metadata_path(rhs, lhs);
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensor_consumers_through_view(
        const ggml_backend_hrx_loom_op_request * request,
        const ggml_tensor * owner,
        const ggml_tensor * view) {
    return ggml_backend_hrx_loom_tensor_consumers_through_view_cached(
        request, owner, view);
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensor_is_transient_at_indices(
        const ggml_backend_hrx_loom_op_request * request,
        const ggml_tensor * tensor,
        const int * consumed_node_indices,
        int consumed_node_count) {
    return ggml_backend_hrx_loom_tensor_is_transient_at_indices_cached(
        request, tensor, consumed_node_indices, consumed_node_count);
}

[[maybe_unused]] static bool ggml_backend_hrx_loom_tensor_is_transient(
        const ggml_backend_hrx_loom_op_request * request,
        const ggml_tensor * tensor,
        int matched_node_count) {
    if (!request || !request->cgraph || !tensor || request->node_index < 0 || matched_node_count <= 0) {
        return false;
    }
    if (matched_node_count > GGML_BACKEND_HRX_LOOM_MAX_CONSUMED_NODES ||
        request->node_index + matched_node_count > request->cgraph->n_nodes) {
        return false;
    }
    int consumed_node_indices[GGML_BACKEND_HRX_LOOM_MAX_CONSUMED_NODES] = {};
    for (int i = 0; i < matched_node_count; ++i) {
        consumed_node_indices[i] = request->node_index + i;
    }
    return ggml_backend_hrx_loom_tensor_is_transient_at_indices(
        request,
        tensor,
        consumed_node_indices,
        matched_node_count);
}
"""

DISPATCHER_FUNCTION_OPEN_TEMPLATE = """ggml_backend_hrx_loom_op_response ggml_backend_hrx_loom_match_or_prepare_request(
        ggml_backend_hrx_loom_catalog * catalog,
        const ggml_backend_hrx_loom_op_request * request,
        ggml_backend_hrx_loom_execution_plan * plan) {
    if (!catalog || !request || !request->op) {
        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
    }

    switch (request->op->op) {"""

DISPATCHER_FUNCTION_CLOSE_TEMPLATE = """        default:
            break;
    }
    return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);
}
"""


cpp_string = route_emit.cpp_string


def c_identifier(value):
    return route_emit.c_identifier(value)


def route_function_name(route_id):
    return f"ggml_backend_hrx_loom_route_{c_identifier(route_id)}"


def op_router_function_name(op):
    op_name = op
    if op_name.startswith("GGML_OP_"):
        op_name = op_name[len("GGML_OP_"):]
    return f"ggml_backend_hrx_loom_router_{c_identifier(op_name).lower()}"


def route_id_constant(route_id):
    return f"GGML_HRX_LOOM_ROUTE_ID_{c_identifier(route_id).upper()}"


def route_response(reason):
    return f"return ggml_backend_hrx_loom_unsupported({reason});"


def failed_response(route_constant):
    return f"return ggml_backend_hrx_loom_failed({route_constant});"


def load_route(source_root, route_name):
    source_root = source_root.resolve()
    route_path = Path(route_name)
    if not route_path.is_absolute():
        route_path = source_root / route_path
    route_path = route_path.resolve()

    metadata_targets = route_validator.load_metadata_targets(source_root)
    definitions = route_validator.load_definitions(source_root)
    route_validator.validate_route(
        route_path, definitions, metadata_targets,
        route_validator.load_storage_transform_ids(source_root))
    route = route_schema.read_json(route_path)
    definition_path = (route_path.parent / route_schema.require_string(route, "definition", route_path)).resolve()
    definition = definitions[definition_path]
    return route_path, route, definition_path, definition


def scalar_offsets(scalars, route_path):
    return route_emit.scalar_offsets(scalars, route_path, route_schema)


def typed_expr(expr, scalar_type):
    return route_emit.typed_expr(expr, scalar_type)


def scalar_literal(value, scalar_type):
    return route_emit.scalar_literal(value, scalar_type)


def source_expr(source):
    return route_emit.source_expr(source)


def config_value_expr(binding):
    scalar_type = route_schema.require_string(binding, "type", "route")
    if "source" in binding:
        return typed_expr(source_expr(route_schema.require_string(binding, "source", "route")), scalar_type)
    return scalar_literal(binding["value"], scalar_type)


def config_format_args(value_var, scalar_type):
    if scalar_type in {"i32", "i64"}:
        return '"%lld"', f"static_cast<long long>({value_var})"
    if scalar_type == "f32":
        return '"%.9g"', f"static_cast<double>({value_var})"
    if scalar_type == "f64":
        return '"%.17g"', value_var
    raise ValueError(f"unsupported config type {scalar_type}")


def config_value_var(binding, prefix):
    return (
        f"{prefix}_config_"
        f"{c_identifier(route_schema.require_string(binding, 'name', 'route'))}_value"
    )


def config_text_var(binding, prefix):
    return (
        f"{prefix}_config_"
        f"{c_identifier(route_schema.require_string(binding, 'name', 'route'))}_text"
    )


def config_length_var(binding, prefix):
    return (
        f"{prefix}_config_"
        f"{c_identifier(route_schema.require_string(binding, 'name', 'route'))}_length"
    )


def emit_config_materialization(lines, owner, prefix):
    config = route_schema.require_dict(owner, "config", "route")
    bindings = route_schema.require_array(config, "bindings", "route")
    for binding in bindings:
        scalar_type = route_schema.require_string(binding, "type", "route")
        cpp_type = CPP_SCALAR_TYPES[scalar_type]
        value_var = config_value_var(binding, prefix)
        text_var = config_text_var(binding, prefix)
        length_var = config_length_var(binding, prefix)
        format_text, format_value = config_format_args(value_var, scalar_type)
        lines.extend([
            f"    const {cpp_type} {value_var} = {config_value_expr(binding)};",
            f"    char {text_var}[128] = {{}};",
            f"    const int {length_var} = std::snprintf({text_var}, sizeof({text_var}), {format_text}, {format_value});",
            f"    if ({length_var} < 0 || static_cast<size_t>({length_var}) >= sizeof({text_var})) {{",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_CONFIG);",
            "    }",
        ])


def emit_config_plan_copy(lines, owner, plan_expr, prefix):
    config = route_schema.require_dict(owner, "config", "route")
    bindings = route_schema.require_array(config, "bindings", "route")
    for i, binding in enumerate(bindings):
        name = route_schema.require_string(binding, "name", "route")
        scalar_type = route_schema.require_string(binding, "type", "route")
        text_var = config_text_var(binding, prefix)
        lines.extend([
            f"    std::memcpy({plan_expr}.config_bindings[{i}].name, {cpp_string(name)}, sizeof({cpp_string(name)}));",
            f"    std::memcpy({plan_expr}.config_bindings[{i}].value, {text_var}, "
            f"static_cast<size_t>({config_length_var(binding, prefix)}) + 1);",
            f"    {plan_expr}.config_bindings[{i}].type = {cpp_string(scalar_type)};",
        ])
    lines.append(f"    {plan_expr}.config_binding_count = {len(bindings)};")


def emit_integer_operand(value, context):
    return route_emit.emit_integer_operand(value, context, route_schema)


def scratch_var(prefix, scratch_name, segment_name, field):
    return (
        f"{prefix}_scratch_{c_identifier(scratch_name)}_"
        f"{c_identifier(segment_name)}_{field}"
    )


def emit_scratch_plans(lines, route, context, route_constant):
    scratch = route_schema.validate_scratch(route, "route", context)
    segment_layout = {}
    for scratch_name, scratch_class in scratch.items():
        scratch_index = scratch_class["index"]
        previous_end = "0"
        for segment in scratch_class["segments"]:
            segment_name = segment["name"]
            value_var = scratch_var("route", scratch_name, segment_name, "length_value")
            length_var = scratch_var("route", scratch_name, segment_name, "length")
            offset_var = scratch_var("route", scratch_name, segment_name, "offset")
            end_var = scratch_var("route", scratch_name, segment_name, "end")
            length_expr = emit_integer_operand(segment["length"], context)
            alignment = segment["alignment"]
            lines.extend([
                f"    const int64_t {value_var} = static_cast<int64_t>({length_expr});",
                f"    if ({value_var} <= 0) {{",
                f"        {failed_response(route_constant)}",
                "    }",
                f"    const size_t {length_var} = static_cast<size_t>({value_var});",
                f"    if ({previous_end} > SIZE_MAX - {alignment - 1}) {{",
                f"        {failed_response(route_constant)}",
                "    }",
                f"    const size_t {offset_var} = "
                f"({previous_end} + {alignment - 1}) / {alignment} * {alignment};",
                f"    if ({length_var} > SIZE_MAX - {offset_var}) {{",
                f"        {failed_response(route_constant)}",
                "    }",
                f"    const size_t {end_var} = {offset_var} + {length_var};",
            ])
            segment_layout[f"{scratch_name}.{segment_name}"] = {
                "scratch_index": scratch_index,
                "offset": offset_var,
                "length": length_var,
            }
            previous_end = end_var
        lines.extend([
            f"    plan->scratch[{scratch_index}].name = {cpp_string(scratch_name)};",
            f"    plan->scratch[{scratch_index}].bytes = {previous_end};",
            f"    plan->scratch[{scratch_index}].minimum_capacity = "
            f"{scratch_class['minimum_capacity']};",
        ])
    lines.append(f"    plan->scratch_count = {len(scratch)};")
    return scratch, segment_layout


def emit_dispatch_plan(
        lines,
        dispatch,
        context,
        plan_expr,
        entry_expr,
        prefix,
        route_constant):
    if "work_items" in dispatch:
        helper = "ggml_backend_hrx_make_work_items_dispatch_config"
        values = route_schema.require_array(dispatch, "work_items", "route")
        value_name = f"{prefix}_dispatch_work_items"
    else:
        helper = "ggml_backend_hrx_make_workgroup_dispatch_config"
        values = route_schema.require_array(dispatch, "workgroups", "route")
        value_name = f"{prefix}_dispatch_workgroups"
    x, y, z = route_emit.dispatch_axis_exprs(values, context, route_schema)
    lines.extend([
        f"    const int64_t {value_name}[3] = {{{x}, {y}, {z}}};",
        f"    if (!{helper}({entry_expr}->workgroup_size, {value_name}, "
        f"&{plan_expr}.dispatch)) {{",
        f"        {failed_response(route_constant)}",
        "    }",
    ])


def emit_kernel_plan(
        lines,
        owner,
        definition,
        context,
        plan_expr,
        entry_expr,
        prefix,
        segment_layout,
        route_constant,
        track_deferred_accesses=False,
        internal_read_tensors=frozenset()):
    invocation = route_schema.require_dict(owner, "invocation", "route")
    buffers = sorted(route_schema.require_array(invocation, "buffers", "route"), key=lambda item: item["position"])
    scalars = sorted(route_schema.require_array(invocation, "scalars", "route"), key=lambda item: item["position"])
    dispatch = route_schema.require_dict(invocation, "dispatch", "route")
    abi = route_schema.require_dict(definition, "abi", "definition")
    constant_byte_length = route_schema.require_int(abi, "constant_byte_length", "definition")
    offsets, constants_size = scalar_offsets(scalars, "route")
    if constants_size != constant_byte_length:
        raise ValueError(f"route scalar size {constants_size} does not match definition constant bytes {constant_byte_length}")

    lines.append(f"    {plan_expr}.entry = {entry_expr};")
    emit_config_materialization(lines, owner, prefix)
    emit_config_plan_copy(lines, owner, plan_expr, prefix)

    deferred_read_mask = 0
    deferred_write_mask = 0
    for buffer in buffers:
        position = route_schema.require_int(buffer, "position", "route")
        kind = route_schema.require_string(buffer, "kind", "route")
        if "tensor" in buffer:
            tensor = route_schema.require_string(buffer, "tensor", "route")
            tensor_var = route_emit.role_var(tensor)
            lines.append(BIND_BUFFER_TEMPLATE.format(
                plan_expr=plan_expr,
                tensor=tensor_var,
                position=position,
                route_id_constant=route_constant,
            ))
            if (
                track_deferred_accesses and
                kind in {"input", "inout"} and
                tensor not in internal_read_tensors
            ):
                lines.append(
                    f"    {plan_expr}.deferred_read_tensors[{position}] = "
                    f"{tensor_var};"
                )
                deferred_read_mask |= 1 << position
            if track_deferred_accesses and kind in {"output", "inout"}:
                lines.append(
                    f"    {plan_expr}.deferred_write_tensors[{position}] = "
                    f"{tensor_var};"
                )
                deferred_write_mask |= 1 << position
        else:
            reference = route_schema.require_string(buffer, "scratch", "route")
            layout = segment_layout[reference]
            lines.extend([
                f"    {plan_expr}.binding_scratch_index[{position}] = "
                f"{layout['scratch_index'] + 1};",
                f"    {plan_expr}.binding_scratch_offset[{position}] = "
                f"{layout['offset']};",
                f"    {plan_expr}.binding_scratch_length[{position}] = "
                f"{layout['length']};",
            ])
    if track_deferred_accesses:
        lines.append(
            f"    {plan_expr}.deferred_read_binding_mask = "
            f"{deferred_read_mask};"
        )
        lines.append(
            f"    {plan_expr}.deferred_write_binding_mask = "
            f"{deferred_write_mask};"
        )
    lines.append(f"    {plan_expr}.binding_count = {len(buffers)};")

    for scalar, offset in zip(scalars, offsets):
        name = route_schema.require_string(scalar, "name", "route")
        scalar_type = route_schema.require_string(scalar, "type", "route")
        cpp_type = CPP_SCALAR_TYPES[scalar_type]
        if "source" in scalar:
            value = typed_expr(source_expr(route_schema.require_string(scalar, "source", "route")), scalar_type)
        else:
            value = scalar_literal(scalar["value"], scalar_type)
        temp = f"{prefix}_constant_{c_identifier(name)}"
        lines.append(PACK_SCALAR_TEMPLATE.format(
            cpp_type=cpp_type,
            name=temp,
            value=value,
            offset=offset,
            plan_expr=plan_expr,
        ))
    lines.append(f"    {plan_expr}.constants_size = {constant_byte_length};")

    emit_dispatch_plan(
        lines,
        dispatch,
        context,
        plan_expr,
        entry_expr,
        prefix,
        route_constant,
    )


def emit_consumed_nodes(lines, consumed_node_indices):
    if len(consumed_node_indices) > route_schema.MAX_CONSUMED_NODES:
        raise ValueError(
            f"route consumes too many graph nodes: {len(consumed_node_indices)}"
        )
    lines.append(f"    plan->consumed_node_count = {len(consumed_node_indices)};")
    for i, node_index in enumerate(consumed_node_indices):
        lines.append(f"    plan->consumed_node_indices[{i}] = {node_index};")


def load_prepass_definitions(route_path, route):
    result = []
    for i, prepass in enumerate(route.get("prepasses", [])):
        source = f"{route_path}: prepasses[{i}]"
        definition_path = (
            route_path.parent /
            route_schema.require_string(prepass, "definition", source)
        ).resolve()
        result.append((prepass, definition_path, route_schema.read_json(definition_path)))
    return result


def deferred_stage_internal_read_tensors(prepasses):
    guaranteed_outputs = set()
    internal_reads = []
    for prepass, _, _ in prepasses:
        internal_reads.append(frozenset(guaranteed_outputs))
        if "cache" in prepass:
            continue
        invocation = route_schema.require_dict(
            prepass, "invocation", "route"
        )
        for buffer in route_schema.require_array(
                invocation, "buffers", "route"):
            if (
                "tensor" in buffer and
                route_schema.require_string(
                    buffer, "kind", "route"
                ) in {"output", "inout"}
            ):
                guaranteed_outputs.add(
                    route_schema.require_string(
                        buffer, "tensor", "route"
                    )
                )
    return internal_reads, frozenset(guaranteed_outputs)


def emit_prepass_entry_lookups(lines, route_path, prepasses):
    for i, (prepass, _, _) in enumerate(prepasses):
        prepass_id = route_schema.require_string(
            prepass,
            "id",
            f"{route_path}: prepasses[{i}]",
        )
        lines.extend([
            f"    const ggml_backend_hrx_loom_catalog_entry * prepass_entry_{i} =",
            f"        ggml_backend_hrx_loom_find_entry(catalog, {cpp_string(prepass_id)});",
            f"    if (!prepass_entry_{i}) {{",
            "        return ggml_backend_hrx_loom_unsupported("
            "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_TARGET);",
            "    }",
        ])


def emit_prepass_plans(
        lines,
        route_path,
        prepasses,
        scratch,
        segment_layout,
        context,
        route_constant,
        track_deferred_accesses=False,
        internal_read_tensors=()):
    for i, (prepass, _, prepass_definition) in enumerate(prepasses):
        prepass_plan = f"plan->prepasses[{i}]"
        emit_kernel_plan(
            lines,
            prepass,
            prepass_definition,
            context,
            f"{prepass_plan}.kernel",
            f"prepass_entry_{i}",
            f"prepass_{i}",
            segment_layout,
            route_constant,
            track_deferred_accesses,
            internal_read_tensors[i] if track_deferred_accesses else frozenset(),
        )
        if "cache" not in prepass:
            continue
        cache = route_schema.require_dict(
            prepass,
            "cache",
            f"{route_path}: prepasses[{i}]",
        )
        cache_scratch = route_schema.require_string(cache, "scratch", "route")
        cache_tensor = route_schema.require_string(cache, "tensor", "route")
        region = cache.get("region")
        lines.extend([
            f"    {prepass_plan}.cache_scratch_index = "
            f"{scratch[cache_scratch]['index'] + 1};",
        ])
        if region is not None:
            offset_expr = emit_integer_operand(region.get("offset", 0), context)
            length_expr = emit_integer_operand(region["length"], context)
            lines.extend([
                f"    const int64_t prepass_{i}_cache_region_offset = "
                f"static_cast<int64_t>({offset_expr});",
                f"    const int64_t prepass_{i}_cache_region_length = "
                f"static_cast<int64_t>({length_expr});",
                f"    if (prepass_{i}_cache_region_offset < 0 || "
                f"prepass_{i}_cache_region_length <= 0 ||",
                f"        static_cast<uint64_t>(prepass_{i}_cache_region_offset) > SIZE_MAX || "
                f"static_cast<uint64_t>(prepass_{i}_cache_region_length) > SIZE_MAX) {{",
                f"        {failed_response(route_constant)}",
                "    }",
                f"    {prepass_plan}.cache_region_offset = "
                f"static_cast<size_t>(prepass_{i}_cache_region_offset);",
                f"    {prepass_plan}.cache_region_length = "
                f"static_cast<size_t>(prepass_{i}_cache_region_length);",
            ])
        lines.extend([
            f"    {prepass_plan}.cache_source = {route_emit.role_var(cache_tensor)};",
            f"    if (!ggml_backend_hrx_loom_bind_tensor(request, "
            f"{route_emit.role_var(cache_tensor)}, &{prepass_plan}.cache_source_binding)) {{",
            f"        {failed_response(route_constant)}",
            "    }",
        ])
    lines.append(f"    plan->prepass_count = {len(prepasses)};")


def fusion_op_var(op_name):
    return f"{c_identifier(op_name)}_op"


def fusion_op_index_var(op_name):
    return f"{c_identifier(op_name)}_op_index"


def fusion_role_expr(op_var, role):
    if role == "dst":
        return op_var
    if role.startswith("src") and role[3:].isdigit():
        return f"{op_var}->src[{int(role[3:])}]"
    raise ValueError(f"unsupported tensor role {role}")


def emit_required_fusion_tensors(lines, route):
    tensors = route_schema.route_tensors(route, "route")
    required = sorted(
        name for name, tensor in tensors.items()
        if not tensor.get("optional", False)
    )
    if required:
        condition = " || ".join(
            [f"!{route_emit.role_var(name)}" for name in required]
        )
        lines.extend([
            f"    if ({condition}) {{",
            "        return ggml_backend_hrx_loom_unsupported("
            "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE);",
            "    }",
        ])


def emit_consecutive_fusion_op_setup(lines, route, route_constant):
    del route_constant
    match = route_schema.require_dict(route, "match", "route")
    ops = route_schema.require_dict(match, "ops", "route")
    op_names = list(ops)
    matched_node_count = len(op_names)
    lines.extend([
        f"    static constexpr int matched_node_count = {matched_node_count};",
        "    if (!request->cgraph || request->node_index < 0 ||",
        "            request->node_index + matched_node_count > request->cgraph->n_nodes ||",
        "            request->cgraph->nodes[request->node_index] != node) {",
        "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
        "    }",
    ])
    for i, op_name in enumerate(op_names):
        op_match = route_schema.require_dict(ops[op_name], "tensors", "route")
        del op_match
        op = route_schema.require_string(ops[op_name], "op", "route")
        op_var = fusion_op_var(op_name)
        source = "node" if i == 0 else f"request->cgraph->nodes[request->node_index + {i}]"
        lines.extend([
            f"    const ggml_tensor * {op_var} = {source};",
            f"    if (!{op_var} || {op_var}->op != {op}) {{",
            "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
            "    }",
        ])

    assigned = {}
    for op_name, op_match in ops.items():
        op_var = fusion_op_var(op_name)
        op_tensors = route_schema.require_dict(op_match, "tensors", "route")
        for role, tensor_name in op_tensors.items():
            expr = fusion_role_expr(op_var, role)
            tensor_var = route_emit.role_var(tensor_name)
            if tensor_name not in assigned:
                assigned[tensor_name] = expr
                lines.append(f"    const ggml_tensor * {tensor_var} = {expr};")
            else:
                lines.extend([
                    f"    if ({tensor_var} != {expr}) {{",
                    "        return ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE);",
                    "    }",
                ])

    emit_required_fusion_tensors(lines, route)
    return {
        op_name: f"request->node_index + {i}"
        for i, op_name in enumerate(op_names)
    }


def emit_tensor_dag_fusion_op_setup(lines, route, route_constant):
    del route_constant
    match = route_schema.require_dict(route, "match", "route")
    ops = route_schema.require_dict(match, "ops", "route")
    op_names = list(ops)
    anchor_name = op_names[0]
    anchor_var = fusion_op_var(anchor_name)
    anchor_index = fusion_op_index_var(anchor_name)

    lines.extend([
        f"    [[maybe_unused]] static constexpr int matched_node_count = "
        f"{len(op_names)};",
        "    if (!request->cgraph || request->node_index < 0 ||",
        "            request->node_index >= request->cgraph->n_nodes ||",
        "            request->cgraph->nodes[request->node_index] != node) {",
        "        return ggml_backend_hrx_loom_unsupported("
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
        "    }",
        f"    const ggml_tensor * {anchor_var} = node;",
        f"    [[maybe_unused]] const int {anchor_index} = request->node_index;",
    ])

    assigned = {}

    def bind_op_tensors(op_name):
        op_var = fusion_op_var(op_name)
        op_tensors = route_schema.require_dict(
            ops[op_name], "tensors", "route"
        )
        for role, tensor_name in op_tensors.items():
            expr = fusion_role_expr(op_var, role)
            tensor_var = route_emit.role_var(tensor_name)
            if tensor_name not in assigned:
                assigned[tensor_name] = expr
                lines.append(
                    f"    const ggml_tensor * {tensor_var} = {expr};"
                )
                continue
            lines.extend([
                "    if (!(ggml_backend_hrx_loom_tensor_dag_edge_matches("
                f"{tensor_var}, {expr}))) {{",
                "        return ggml_backend_hrx_loom_unsupported("
                "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE);",
                "    }",
            ])

    bind_op_tensors(anchor_name)
    resolved_names = [anchor_name]
    consumed_ops = set(match.get("consumed_ops", op_names))
    metadata_ops = {
        "GGML_OP_RESHAPE",
        "GGML_OP_VIEW",
        "GGML_OP_PERMUTE",
        "GGML_OP_TRANSPOSE",
    }

    for op_name in op_names[1:]:
        op_match = ops[op_name]
        op = route_schema.require_string(op_match, "op", "route")
        op_var = fusion_op_var(op_name)
        op_index = fusion_op_index_var(op_name)
        op_tensors = route_schema.require_dict(op_match, "tensors", "route")
        shared = [
            (role, tensor_name)
            for role, tensor_name in op_tensors.items()
            if tensor_name in assigned
        ]
        lines.extend([
            f"    const ggml_tensor * {op_var} = nullptr;",
            f"    [[maybe_unused]] int {op_index} = -1;",
            "    for (int candidate_index = 0; "
            "candidate_index < request->cgraph->n_nodes; ++candidate_index) {",
            "        const ggml_tensor * candidate = "
            "request->cgraph->nodes[candidate_index];",
        ])
        rejected = [
            "!candidate",
            f"candidate->op != {op}",
            *[
                f"candidate == {fusion_op_var(resolved_name)}"
                for resolved_name in resolved_names
            ],
            *[
                "!ggml_backend_hrx_loom_tensor_dag_edge_matches("
                f"{fusion_role_expr('candidate', role)}, "
                f"{route_emit.role_var(tensor_name)})"
                for role, tensor_name in shared
            ],
        ]
        lines.extend([
            f"        if ({' || '.join(rejected)}) {{",
            "            continue;",
            "        }",
        ])

        # Compose every declared edge from a consumed candidate to an
        # unconsumed compute op as a structural witness. If the consumer was
        # already resolved, check that exact op; otherwise search the graph.
        # This follows the route DAG, independent of dispatch timing and JSON
        # declaration order.
        witnesses = []
        if op_name in consumed_ops:
            dst_tensor = op_tensors.get("dst")
            for witness_name in op_names:
                if witness_name == op_name:
                    continue
                witness_match = ops[witness_name]
                witness_op = route_schema.require_string(
                    witness_match, "op", "route"
                )
                witness_tensors = route_schema.require_dict(
                    witness_match, "tensors", "route"
                )
                witness_inputs = {
                    tensor_name
                    for role, tensor_name in witness_tensors.items()
                    if role != "dst"
                }
                if (
                    witness_name not in consumed_ops and
                    witness_op not in metadata_ops and
                    dst_tensor in witness_inputs
                ):
                    witnesses.append((
                        witness_name,
                        witness_op,
                        witness_tensors,
                        dst_tensor,
                    ))

        for witness_name, witness_op, witness_tensors, dst_tensor in witnesses:
            witness_id = c_identifier(witness_name)
            current_role = next(
                role
                for role, tensor_name in op_tensors.items()
                if tensor_name == dst_tensor
            )
            witness_shared = [
                (role, tensor_name)
                for role, tensor_name in witness_tensors.items()
                if tensor_name in assigned or tensor_name == dst_tensor
            ]
            if witness_name in resolved_names:
                direct_rejected = []
                for role, tensor_name in witness_shared:
                    source_expr = (
                        fusion_role_expr("candidate", current_role)
                        if tensor_name == dst_tensor
                        else route_emit.role_var(tensor_name)
                    )
                    direct_rejected.append(
                        "!ggml_backend_hrx_loom_tensor_dag_edge_matches("
                        f"{fusion_role_expr(fusion_op_var(witness_name), role)}, "
                        f"{source_expr})"
                    )
                if direct_rejected:
                    lines.extend([
                        f"        if ({' || '.join(direct_rejected)}) {{",
                        "            continue;",
                        "        }",
                    ])
                continue
            witness_rejected = [
                f"!{witness_id}_candidate",
                f"{witness_id}_candidate->op != {witness_op}",
                f"{witness_id}_candidate == candidate",
                *[
                    f"{witness_id}_candidate == "
                    f"{fusion_op_var(resolved_name)}"
                    for resolved_name in resolved_names
                ],
            ]
            for role, tensor_name in witness_shared:
                source_expr = (
                    fusion_role_expr("candidate", current_role)
                    if tensor_name == dst_tensor
                    else route_emit.role_var(tensor_name)
                )
                witness_rejected.append(
                    "!ggml_backend_hrx_loom_tensor_dag_edge_matches("
                    f"{fusion_role_expr(f'{witness_id}_candidate', role)}, "
                    f"{source_expr})"
                )
            lines.extend([
                f"        bool candidate_has_{witness_id}_witness = false;",
                f"        for (int {witness_id}_witness_index = 0;",
                f"                {witness_id}_witness_index < "
                "request->cgraph->n_nodes;",
                f"                ++{witness_id}_witness_index) {{",
                f"            const ggml_tensor * {witness_id}_candidate =",
                "                request->cgraph->nodes["
                f"{witness_id}_witness_index];",
                f"            if ({' || '.join(witness_rejected)}) {{",
                "                continue;",
                "            }",
                f"            candidate_has_{witness_id}_witness = true;",
                "            break;",
                "        }",
                f"        if (!candidate_has_{witness_id}_witness) {{",
                "            continue;",
                "        }",
            ])

        lines.extend([
            f"        if ({op_var}) {{",
            "            return ggml_backend_hrx_loom_unsupported("
            "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
            "        }",
            f"        {op_var} = candidate;",
            f"        {op_index} = candidate_index;",
            "    }",
            f"    if (!{op_var}) {{",
            "        return ggml_backend_hrx_loom_unsupported("
            "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
            "    }",
        ])
        bind_op_tensors(op_name)
        resolved_names.append(op_name)

    emit_required_fusion_tensors(lines, route)
    return {
        op_name: fusion_op_index_var(op_name)
        for op_name in op_names
    }


def emit_fusion_op_setup(lines, route, route_constant):
    match = route_schema.require_dict(route, "match", "route")
    traversal = route_schema.fusion_traversal(match, "route: match")
    if traversal == "tensor_dag":
        return emit_tensor_dag_fusion_op_setup(
            lines, route, route_constant
        )
    return emit_consecutive_fusion_op_setup(lines, route, route_constant)


def emit_fusion_consumed_index_array(lines, consumed_node_indices):
    lines.extend([
        f"    static constexpr int consumed_node_count = "
        f"{len(consumed_node_indices)};",
        "    const int consumed_node_indices[consumed_node_count] = {"
        f"{', '.join(consumed_node_indices)}}};",
    ])
    condition = " || ".join(
        f"{node_index} < request->node_index"
        for node_index in consumed_node_indices
    )
    lines.extend([
        f"    if ({condition}) {{",
        "        return ggml_backend_hrx_loom_unsupported("
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
        "    }",
    ])


def emit_fusion_attributes(lines, route):
    match = route_schema.require_dict(route, "match", "route")
    ops = route_schema.require_dict(match, "ops", "route")
    for op_name, op_match in ops.items():
        op = route_schema.require_string(op_match, "op", "route")
        attributes = op_match.get("attributes", {})
        if not attributes:
            continue
        indices = ATTRIBUTE_INDICES[op]
        op_var = fusion_op_var(op_name)
        for name, attr in attributes.items():
            scalar_type = route_schema.require_string(attr, "type", "route")
            getter = route_emit.ATTRIBUTE_GETTERS[scalar_type]
            cast = CPP_SCALAR_TYPES[scalar_type]
            lines.append(f"    const {cast} {route_emit.fusion_attribute_var(op_name, name)} = {getter}({op_var}, {indices[name]});")


def generate_fusion_route_impl(route_path, route, definition):
    match = route_schema.require_dict(route, "match", route_path)
    ops = route_schema.require_dict(match, "ops", route_path)
    traversal = route_schema.fusion_traversal(match, f"{route_path}: match")
    consumed_ops = route_schema.fusion_consumed_ops(
        match, ops, f"{route_path}: match"
    )
    dispatch_owner = route_schema.fusion_dispatch_owner(
        match,
        ops,
        consumed_ops,
        f"{route_path}: match",
    )
    anchors = match.get("anchors", [])
    anchor_name = anchors[0] if anchors else next(iter(ops))
    anchor_op = route_schema.require_string(ops[anchor_name], "op", route_path)
    route_id = route_schema.require_string(route, "id", route_path)
    function_name = route_function_name(route_id)
    route_constant = route_id_constant(route_id)
    prepasses = load_prepass_definitions(route_path, route)
    prepass_internal_reads, main_internal_reads = (
        deferred_stage_internal_read_tensors(prepasses)
        if dispatch_owner is not None
        else ([], frozenset())
    )
    context = route_schema.FusionRouteContext(
        route_path,
        route_schema.route_tensors(route, route_path),
        {op_name: op_match.get("attributes", {}) for op_name, op_match in ops.items()},
        route_schema.require_dict(route, "derived", route_path),
    )

    lines = []
    lines.append(ROUTE_FUNCTION_OPEN_TEMPLATE.format(
        function_name=function_name,
        op=anchor_op,
        route_id_constant=route_constant,
    ))
    emit_prepass_entry_lookups(lines, route_path, prepasses)
    op_indices = emit_fusion_op_setup(lines, route, route_constant)
    consumed_node_indices = [
        op_indices[op_name] for op_name in consumed_ops
    ]
    if traversal == "tensor_dag" or "consumed_ops" in match:
        emit_fusion_consumed_index_array(lines, consumed_node_indices)
        context.transient_node_indices = "consumed_node_indices"
        context.transient_node_count = "consumed_node_count"
    route_emit.emit_dtype_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_DTYPE",
    )
    route_emit.emit_storage_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    )
    emit_fusion_attributes(lines, route)
    route_emit.emit_shape_captures(lines, route, route_schema)
    route_emit.emit_tensor_declaration_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    )
    route_emit.emit_derived(lines, route, context, route_schema, "ggml_backend_hrx_loom_next_power_of_2")
    route_emit.emit_predicates(lines, route, context, route_schema, UNSUPPORTED_REASON_BY_PREDICATE, route_response)
    lines.append(PLAN_SETUP_TEMPLATE.format(route_id_constant=route_constant))
    scratch, segment_layout = emit_scratch_plans(
        lines,
        route,
        context,
        route_constant,
    )
    emit_kernel_plan(
        lines,
        route,
        definition,
        context,
        "plan->main",
        "entry",
        "main",
        segment_layout,
        route_constant,
        dispatch_owner is not None,
        main_internal_reads,
    )
    emit_consumed_nodes(
        lines,
        consumed_node_indices,
    )
    if dispatch_owner is not None:
        lines.append(
            "    plan->dispatch_owner_node_index = "
            f"{op_indices[dispatch_owner]};"
        )
    emit_prepass_plans(
        lines,
        route_path,
        prepasses,
        scratch,
        segment_layout,
        context,
        route_constant,
        dispatch_owner is not None,
        prepass_internal_reads,
    )
    lines.append(f"    return ggml_backend_hrx_loom_supported({route_constant});")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_route_impl(route_path, route, definition):
    route_emit.validate_attribute_indices(route, route_path, route_schema, ATTRIBUTE_INDICES)
    if route_schema.route_is_fusion_v2(route, route_path):
        return generate_fusion_route_impl(route_path, route, definition)

    match = route_schema.require_dict(route, "match", route_path)
    op = route_schema.require_string(match, "op", f"{route_path}: match")
    op_rule = route_schema.OP_RULES[op]
    route_id = route_schema.require_string(route, "id", route_path)
    function_name = route_function_name(route_id)
    route_constant = route_id_constant(route_id)
    prepasses = load_prepass_definitions(route_path, route)
    context = route_schema.RouteContext(
        route_path,
        op_rule,
        route_schema.route_tensors(route, route_path),
        match.get("attributes", {}),
        route_schema.require_dict(route, "derived", route_path),
    )

    lines = []
    lines.append(ROUTE_FUNCTION_OPEN_TEMPLATE.format(
        function_name=function_name,
        op=op,
        route_id_constant=route_constant,
    ))
    emit_prepass_entry_lookups(lines, route_path, prepasses)
    route_emit.emit_tensor_setup(
        lines,
        route,
        op_rule,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
    )
    route_emit.emit_dtype_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_DTYPE",
    )
    route_emit.emit_storage_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    )
    route_emit.emit_attributes(lines, route, route_schema, ATTRIBUTE_INDICES)
    route_emit.emit_shape_captures(lines, route, route_schema)
    route_emit.emit_tensor_declaration_checks(
        lines,
        route,
        route_schema,
        route_response,
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_SHAPE",
        "GGML_BACKEND_HRX_LOOM_UNSUPPORTED_LAYOUT",
    )
    route_emit.emit_derived(lines, route, context, route_schema, "ggml_backend_hrx_loom_next_power_of_2")
    route_emit.emit_predicates(lines, route, context, route_schema, UNSUPPORTED_REASON_BY_PREDICATE, route_response)
    lines.append(PLAN_SETUP_TEMPLATE.format(route_id_constant=route_constant))
    scratch, segment_layout = emit_scratch_plans(
        lines,
        route,
        context,
        route_constant,
    )
    emit_kernel_plan(
        lines,
        route,
        definition,
        context,
        "plan->main",
        "entry",
        "main",
        segment_layout,
        route_constant,
    )
    emit_consumed_nodes(lines, ["request->node_index"])
    emit_prepass_plans(
        lines,
        route_path,
        prepasses,
        scratch,
        segment_layout,
        context,
        route_constant,
    )
    lines.append(f"    return ggml_backend_hrx_loom_supported({route_constant});")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generate_dispatcher_impl(routes):
    lines = [DISPATCHER_CPP_HEADER_TEMPLATE]
    route_infos = route_emit.route_infos_for_dispatcher(routes, route_schema)
    ops = route_emit.ops_from_route_infos(route_infos)

    for op in ops:
        lines.extend([
            f"ggml_backend_hrx_loom_op_response {op_router_function_name(op)}(",
            "        ggml_backend_hrx_loom_catalog * catalog,",
            "        const ggml_backend_hrx_loom_op_request * request,",
            "        ggml_backend_hrx_loom_execution_plan * plan);",
            "",
        ])

    lines.append(DISPATCHER_FUNCTION_OPEN_TEMPLATE)
    for op in ops:
        lines.extend([
            f"        case {op}:",
            f"            return {op_router_function_name(op)}(catalog, request, plan);",
        ])
    lines.append(DISPATCHER_FUNCTION_CLOSE_TEMPLATE)
    return "\n".join(lines)


def generate_op_router_impl(routes, selected_op):
    lines = [DISPATCHER_CPP_HEADER_TEMPLATE]

    route_infos = route_emit.route_infos_for_op(routes, selected_op, route_schema)
    if not route_infos:
        raise ValueError(f"no routes found for {selected_op}")

    for _, _, route_path, route, definition in route_infos:
        route_id = route_schema.require_string(route, "id", route_path)
        lines.extend([
            f"static constexpr const char * {route_id_constant(route_id)} = {cpp_string(route_id)};",
            "",
            generate_route_impl(route_path, route, definition),
        ])

    function_name = op_router_function_name(selected_op)
    lines.extend([
        f"ggml_backend_hrx_loom_op_response {function_name}(",
        "        ggml_backend_hrx_loom_catalog * catalog,",
        "        const ggml_backend_hrx_loom_op_request * request,",
        "        ggml_backend_hrx_loom_execution_plan * plan);",
        "",
        f"ggml_backend_hrx_loom_op_response {function_name}(",
        "        ggml_backend_hrx_loom_catalog * catalog,",
        "        const ggml_backend_hrx_loom_op_request * request,",
        "        ggml_backend_hrx_loom_execution_plan * plan) {",
        "    ggml_backend_hrx_loom_op_response fallback =",
        "        ggml_backend_hrx_loom_unsupported(GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
        "",
    ])

    for _, route_id, _, _, _ in route_infos:
        lines.extend([
            "    {",
            "        ggml_backend_hrx_loom_op_response response =",
            f"            {route_function_name(route_id)}(catalog, request, plan);",
            "        if (response.result == GGML_BACKEND_HRX_LOOM_INVOKED &&",
            "            !ggml_backend_hrx_loom_plan_can_be_selected(request, plan)) {",
            "            response = ggml_backend_hrx_loom_unsupported(",
            "                GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE);",
            "        }",
            "        if (response.result != GGML_BACKEND_HRX_LOOM_UNSUPPORTED) {",
            "            return response;",
            "        }",
            "        if (fallback.unsupported_reason == GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE &&",
            "            response.unsupported_reason != GGML_BACKEND_HRX_LOOM_UNSUPPORTED_NO_ROUTE) {",
            "            fallback = response;",
            "        }",
            "    }",
            "",
        ])

    lines.extend([
        "    return fallback;",
        "}",
        "",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", default=str(route_validator.default_source_root()))
    parser.add_argument("--route", required=True, action="append")
    parser.add_argument("--out", required=True)
    parser.add_argument("--dispatcher", action="store_true")
    parser.add_argument("--op-router", action="store_true")
    parser.add_argument("--op")
    args = parser.parse_args()

    try:
        routes = [load_route(Path(args.source_root), route_name) for route_name in args.route]
        if args.dispatcher:
            output = generate_dispatcher_impl([(route_path, route, definition) for route_path, route, _, definition in routes])
        elif args.op_router:
            if not args.op:
                raise ValueError("--op-router expects --op")
            output = generate_op_router_impl([(route_path, route, definition) for route_path, route, _, definition in routes], args.op)
        else:
            raise ValueError("expected --dispatcher or --op-router")
        out_path = Path(args.out)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output, encoding="utf-8")
    except (OSError, json.JSONDecodeError, ValueError) as err:
        print(f"ValueError: {err}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
